export const types = {
  PRODUCTS_LOADING: 'SIGNUP_LOADING',
  PRODUCTS: 'PRODUCTS',
  NETWORK_ERROR: 'NETWORK_ERROR',

  INCREASE_CART: 'INCREASE_CART',
  UPDATE_CART_LOADING: 'UPDATE_CART_LOADING',
  DECREASE_CART: 'DECREASE_CART',
};
